doc.go
example/.mage/magefile.go
example/.mage/main.go
example/.mage/tools.mk
example/Makefile
main.go

With this, one can run `go run go.einride.tech/mage-tools` to get everything needed to get started with mage-tools

feat: adds command to generate .mage

---

.github/workflows/go.yml
.mage/magefile.go
targets/mgcocogitto/targets.go
targets/mgconvco/targets.go

Faster than commitlint and free of dependency on Node.JS.

feat: add mgconvco.ConvcoCheck

---

.github/workflows/release.yml

This should make releases work again

fix(cocogitto): add fetch-depth to release pipeline

---

.gitignore
main.go

Fixes https://github.com/einride/mage-tools/issues/45

fix(init): write to gitignore

---

.gitignore
.mage/tools.mk
example/.mage/tools.mk
main.go
mgtool/configuration.go
targets/mgprettier/targets.go

Makes sense to put everything under the .mage dir by default.

feat: move default tools dir under .mage

---

targets/mghadolint/targets.go

See https://github.com/hadolint/hadolint for more information.
No default config has been specified since I don't think we are using
a custom default config right now. Can be added in the future if needed.

feat(hadolint): add Dockerfile linter

---

mgmake/generate.go
targets/mggolangcilint/golangci.yml

- fix(mgmake): include new line when string comparing
- fix(golangcilint): disable thelper

minor fixes

---

mgpath/path.go
targets/mgapilinter/targets.go
targets/mgclangformat/targets.go

- feat: add api-linter
- feat: add clang-format
- feat(mgpath): add changeWorkDir and find file extensions function

add new tools

---

.mage/go.mod
.mage/go.sum
.mage/magefile.go
Makefile
go.mod
go.sum
targets/mgyamlfmt/targets.go

Since we are adding yaml as a dependency in https://github.com/einride/mage-tools/pull/61

feat: add yaml format target

---

example/.mage/magefile.go
example/.mage/mgmake_gen.go
main.go

Closes https://github.com/einride/mage-tools/issues/72

fix(init): add missing import during gen

---

mgpath/path.go
mgtool/build.go
mgtool/configuration.go
targets/mgapilinter/targets.go
targets/mgbuf/targets.go
targets/mgclangformat/targets.go
targets/mgcocogitto/targets.go
targets/mgcommitlint/targets.go
targets/mgconvco/targets.go
targets/mggolangcilint/targets.go
targets/mggolangmigrate/targets.go
targets/mggooglecloudprotoscrubber/targets.go
targets/mggoreview/targets.go
targets/mggrpcjava/targets.go
targets/mghadolint/targets.go
targets/mgko/targets.go
targets/mgmarkdownfmt/targets.go
targets/mgprettier/targets.go
targets/mgprotoc/targets.go
targets/mgsemanticrelease/tool.go
targets/mgsops/targets.go

- chore: add prepare function to each target
- feat: add option to depend on prepare

feat: add prepare target, option to depend on prepare and start symlinking to bin dir

---

Makefile
mgpath/path.go
mgtool/build.go

- feat: add mgtool.GoInstallWithModfile
- feat: update magefile path to bin/

feat: add mgtool.GoInstallWithModfile

---

.mage/magefile.go
cmd/build/main.go
example/.mage/magefile.go
main.go
mglogr/logger.go

feat: simplify and reduce logger API surface

---

cmd/init/example/.github/dependabot.yml
cmd/init/main.go

feat: simplify Dependabot config initialization 

---

.sage/go.mod
.sage/go.sum
.sage/sagefile.go
example/.sage/sagefile.go
go.mod
go.sum
tools/sgyamlfmt/tools.go

Removes runtime dependency on go-yaml.

feat(yamlfmt): migrate to CLI tool

---

Makefile
sg/makefile.go
tools/sgterraform/tools.go

Terraform was not preparing the command﻿

fix(terraform): prepare command on terraform tool

---

sg/exec.go
sg/generate.go
sg/logger.go
sg/makefile.go

Still not a 100% sure what I feel about this one, it does make it easier to understand which command the stdout comes from when running stuff in parallel. But it also just feels not 100% natural when seing the oudput in my terminal :P

feat: pipe stdout and err via logger

---

tools/sggit/tools.go

Will make it easier to see what the diff acutally is.

fix(sggit): show diff in error message

---

sg/exec.go
tools/sgapilinter/api-linter.yaml
tools/sgapilinter/tools.go
tools/sgbuf/tools.go
tools/sggolangcilint/tools.go

Runs the API linter on all Buf modules beneath the current working
directory.

feat(api-linter): add Run helper

---

main.go

fix: remove leading newline from init message

---

Makefile
sg/generate.go
sg/makefile.go

For when you want to manually bump.

feat: add update-sage target

---

.github/workflows/go.yml
.github/workflows/release.yml
actions/setup-go/action.yml
tools/sgcommitlint/tools.go
tools/sgnpmlicense/tools.go
tools/sgprettier/tools.go
tools/sgsemanticrelease/tools.go

With this, we can use something like
```
- name: Set up Go Tooling
uses: einride/sage
cacheKey: build
```

Add GitHub action for setting up the Go toolchain

---

sgtool/file.go

It would be great to be able to use this tool for file downloads that for instance require authentication through headers

feat(file): add http header option to remote file downloads

---

tools/sgko/tools.go

Improvements to multiplatform builds, caching, and more.

feat(ko): bump to 0.10.0

---

sgtool/file.go

This introduces support to use the file tool to fetch remote uncompressed tar archives.

feat(file): support extracting uncompressed tar archives

---

sg/exec.go

This reverts commit 7cf162c2feaeb263020e5594176a90f94139da6c.

Revert "fix(sg): support filepaths from both git root and current working directory"

---

tools/sgapilinter/tools.go
tools/sgclangformat/tools.go
tools/sgshfmt/tools.go

- fix(clang-format): format files from git root even if run from other working dir
- fix(shfmt): format files from git root even if run from other working dir
- chore(api-linter): correct comment

run from git root

---

tools/sgapilinter/tools.go
tools/sgbuf/tools.go
tools/sgconvco/tools.go
tools/sggh/tools.go
tools/sgko/tools.go

- feat(deps): bump ko to 0.11.2
- feat(deps): bump api-linter
- feat(deps): bump buf to 1.1.1
- feat(deps): bump convco to 0.3.9
- feat(deps): bump GitHub CLI to 2.6.0

bump versions

---

.github/dependabot.yml
actions/setup/action.yml

Setup Dependabot to do it automatically.

chore: bump checkout and setup-go

---

tools/sgbuf/tools.go

feat(buf): bump to 1.2.1

---

tools/sgprotocgengoaipdataloader/tools.go
tools/sgprotocgengoaiptest/tools.go

- feat(protoc-gen-go-aip-test): bump to 0.7.2
- feat(protoc-gen-go-aip-dataloader): add tool

proto tools

---

tools/sgapilinter/tools.go

The descriptor build step sometimes fails with context timeout - this
mitigates the flakyness.

fix(api-linter): add basic retry to mitigate flaky buf build

---

tools/sgdbt/tools.go

Install dbt (data build tool) with BigQuery adapter using pip.

feat: add dbt tool

---

tools/sgprotocgengogrpcserviceconfig/tools.go

Includes generated code header.

feat(protoc-gen-go-grpc-service-config): bump to v0.2.2

---

sgtool/file.go

Was originally removed because it is not used in this repo however it does not mean it is not used in other repos and is quite a useful function to have for working with local archive files for tools not yet introduced in this repo

feat: add function to handle local archive files

---

tools/sgprotocgenopenapiv2/tools.go

Generates OpenAPIv2 specs from gRPC services.

feat(sgprotocgenopenapiv2): add tool

---

tools/sggolangcilint/tools.go

latest and greatest :godance:!
https://github.com/golangci/golangci-lint/releases/tag/v1.46.0

feat(sggolangcilint): bump to v1.46.0

---

tools/sgprotocgengoaiptest/tools.go

https://github.com/einride/protoc-gen-go-aip-test/releases/tag/v0.8.0

feat: bump protoc-gen-go-aip-test v0.8.0

---

tools/sgapilinter/tools.go
tools/sgbuf/tools.go

- feat(sgapilinter): bump to v1.33.0
- feat(sgbuf): bump to v1.6.0

feat: bump protobuf tools

---

tools/sgcloudsqlproxy/tool.go

tool for setting up a proxy connection to a cloud sql database to enable secure access

feat: add sgcloudsqlproxy

---

tools/sgcloudrun/config.go
tools/sgyq/tools.go

- feat(sgyq): add package
- feat(sgcloudrun): add sgcloudrun.Develop

feat(sgcloudrun): add sgcloudrun.Develop

---

tools/sgcloudspanner/emulator.go

Starts a dockerized Cloud Spanner emulator and sets the
SPANNER_EMULATOR_HOST environment variable.

feat(sgcloudspanner): add RunEmulator helper

---

tools/sggolangcilint/tools.go

https://github.com/golangci/golangci-lint/releases/tag/v1.47.1

fix(golangcilint): bump to v1.47.1

---

.sage/sagefile.go
example/.sage/sagefile.go
tools/sggoreview/tools.go

Runs the linter for every Go module.

feat: add sggoreview.Run helper

---

tools/sgcloudrun/config.go

For when the command needs additional configuration, e.g. setting the
working directory.

feat(sgcloudrun): add DevelopCommand

---

internal/codegen/file.go
sg/exec.go
sg/internal/runner/runner.go
sgtool/file.go
tools/sgcloudendpoints/deprecated.go
tools/sgcommitlint/tools.go
tools/sggolangcilint/golangci.yml
tools/sggolangcilint/tools.go
tools/sggolangmigrate/tools.go
tools/sggooglecloudprotoscrubber/tools.go
tools/sggoreview/tools.go
tools/sggrpcjava/tools.go
tools/sghadolint/tools.go
tools/sgmarkdownfmt/tools.go
tools/sgnpmlicense/tools.go
tools/sgprettier/tools.go
tools/sgprotoc/tools.go
tools/sgprotocgentypescriptaip/tools.go
tools/sgprotocgentypescripthttp/tools.go
tools/sgsops/tools.go

- feat(deps): bump GolangCI-Lint to 1.48.0
- feat: bump goreview to 0.22.3

Bump linters to support Go 1.19

---

tools/sggolangcilint/tools.go

https://github.com/golangci/golangci-lint/releases/tag/v1.49.0

feat(golangcilint): bump to v1.49.0

---

tools/sgko/tools.go

https://github.com/google/ko/releases/tag/v0.12.0

feat(sgko): bump to v0.12.0

---

tools/sggovulncheck/tools.go

For more info see https://go.dev/blog/vuln

feat: add govulncheck tool

---

.github/workflows/codeql-analysis.yml
sgtool/file.go

adding CodeQL scanning github action

feat: addind codeql

---

actions/setup/action.yml

Nothing more nothing less
Let's see the turnout on this message before merging:
https://einride.slack.com/archives/C02UQKNJBJL/p1666273247678599

feat(ci): default building with Go 1.19

---

sg/deps.go

Saves a list of dependencies in the context and checks whether the function to be executed is in that list already. Very trivial cycle check!
I accidentally created a target that had a circular dependency, and it ended up with a deadlock which I couldn't understand for quite a while. This change makes the same mistake cause a panic instead.
Example sagefile:
```go
func Thing(ctx context.Context) error {
sg.Deps(ctx, Another)
return sg.Command(ctx, "echo", "thing").Run()
}
func Another(ctx context.Context) error {
sg.Deps(ctx, Thing)
return sg.Command(ctx, "echo", "another").Run()
}
```
Call example:
```
$ make thing
[sage] building binary and generating Makefiles...
[thing] dependency cycle calling main.Another! chain: main.Another,main.Thing
make: *** [Makefile:92: thing] Error 1
```

feat: panic if dependency cycle is found

---

tools/sgsqlc/tools.go

Changelog can be found here:
https://github.com/kyleconroy/sqlc/releases/tag/v1.16.0

feat(sqlc): bump to v1.16.0

---

tools/sgbuf/tools.go
tools/sgyamlfmt/tools.go

- feat(buf): bump to v1.9.0
- feat(yamlfmt): bump to 0.6.0

bump versions 2022 11 14

---

tools/sgnpmlicense/tools.go

This will currently break all our builds. So lets get that sorted before merging this.

feat: update license to match gos version

---

tools/sgcloudspanner/emulator.go

The cloudbuild spanner test instance needs
docker inspect to get the host address.

fix(spantest): cloudbuild host address

---

tools/sgosvscanner/tools.go

See
https://security.googleblog.com/2022/12/announcing-osv-scanner-vulnerability.html
for details

feat: add osv-scanner tool

---

tools/sgconvco/tools.go

feat(convco): bump version to 0.3.15

---

.github/CODEOWNERS

chore(codeowners): remove inactive maintainer

---

tools/sgprotocgennetlifycms/tools.go

Generates a Netlify CMS YAML config from proto message schemas.

feat(protobuf-netlify-cms): add Netlify CMS proto generator

---

tools/sgsqlfluff/tools.go

Enables using the dbt templater with sqlfluff.

feat: bump sqlfluff version and add dbt templater deps

---

tools/sgterraform/tools.go

Changelog can be found here:
https://github.com/hashicorp/terraform/blob/main/CHANGELOG.md

fix(terraform) bump to v1.3.7

---

tools/sgbalenacli/tools.go

Old version started printing deprecation notice, so update.

chore(tools): bump balena cli to v15.0.3

---

tools/sgprotocgennetlifycms/tools.go

chore: update protoc-gen-netlify-cms to 0.6.0

---

tools/sgsqlc/tools.go

https://github.com/kyleconroy/sqlc/releases/tag/v1.17.0

feat(sqlc): bump to v1.17.0

---

tools/sggrpcjava/tools.go
tools/sgprotoc/tools.go
tools/sgsqlc/tools.go

Updates:
* protoc-gen-grpc-java
* protoc
* sqlc

fix: use arm64 binaries when available

---

sgtool/file.go

Some zip files do not contain folders as entries in their manifest, and
instead just present their files as explicit entries without
intermediate folders.
We instead run a `MkdirAll` of the parent folder of the file.
This changes the semantics of the `extractZip` function however, as it no 
longer requires that the base path exists.

fix: make sure to be able to unzip files with no folders as entries

---

sg/makefile.go
sgtool/file.go
tools/sgclangformat/tools.go
tools/sggolangcilint/tools.go
tools/sgshellcheck/tools.go

Now with support for generics and those pesky error messages are no longer!

feat(golangcilint): update to v1.52.0

---

tools/sgsqlc/tools.go

https://github.com/kyleconroy/sqlc/releases/tag/v1.18.0

feat(sqlc): bump to v1.18.0

---

tools/sgbetteralign/tools.go

Changes since last update:
[https://github.com/dkorunic/betteralign/releases/tag/v0.2.5
https://github.com/dkorunic/betteralign/releases/tag/v0.2.4](https://github.com/dkorunic/betteralign/compare/v0.2.3...v0.2.5)

fix: update betteralign to v0.2.5

---

tools/sggoreview/tools.go

Hopefully this fixes an intermittent issue where goreview totally failes for no apparent reason.

fix(goreview): bump to v0.23.1

---

tools/sggolangcilint/tools.go

Lots of linter bumps included.

fix(golangcilint): bump to v1.53.2

---

tools/sgcloudendpoints/tools.go

Updated version of Envoy and bug fixes.

feat(cloud-endpoints): bump ESPv2 to 2.44.0

---

tools/sggolangcilint/tools.go

https://github.com/golangci/golangci-lint/releases/tag/v1.53.3

fix(sggolangcilint): bump to v1.53.3

---

.backstage/component.yaml
.sage/main.go
Makefile
tools/sgbackstage/tools.go

Encapsulates default settings (and potential config), which we expect to
change over time.

feat: add Backstage validation helper

---

tools/sgpoetry/command.go
tools/sgpython/command.go

For Python projects managed by Poetry.

feat: add sgpython and sgpoetry tools

---

.gitignore
tools/sgdbt/tools.go
tools/sgsqlfluff/tools.go

- feat(sgdbt): bump dbt-bigquery to 1.6.0
- feat(sgsqlfluff): bump sqlfluff to latest

Bump DBT Deps

---

tools/sggoreview/tools.go

goreview main diff:
- feat: add Backstage metadata
- feat: bump Go to 1.21.0
See full diff below:
https://github.com/einride/goreview/compare/v0.23.1...v0.26.0

feat(goreview): bump to v0.26.0

---

actions/setup/action.yml

chore(actions): use Go 1.21 for setup-sage by default

---

tools/sgterraform/tools.go

GitHub has a limit of 65536 characters in a comment so if the terraform plan exceeded this size (due to too many resource changes for example), only comment summary and point to CI logs for details

feat(sgterraform): do not comment plan if larger than gh supported size

---

tools/sgsqlc/tools.go

Changelog can be found here:
https://github.com/sqlc-dev/sqlc/releases/tag/v1.23.0

feat(sqlc): bump to v1.23.0

---

tools/sgnpmartifactregistryauth/tools.go

relates to [TCC-345](https://einride.atlassian.net/browse/TCC-345)
[TCC-345]: https://einride.atlassian.net/browse/TCC-345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(artifactregistry-auth): use correct binary name and JSON

---

tools/sgmdformat/tools.go

The recursive argument to mdformat (`.`) is quite slow in repos with lots of files and folders where no markdown files are expected to be found. We now instead search for all markdown files that has been checked into the repo (plus untracked files), instead of letting `mdformat` do that.
If you want the previous behaviour you have to pass your own arguments to `Command`.

feat(mdformat): only consider markdown files known to Git

---

tools/sgbackstagecoverage/tools.go
tools/sggcov2lcov/tools.go

Add Backstage coverage reporting command and gcov2lcov tool needed for it.
https://github.com/jandelgado/gcov2lcov

feat: add Backstage Go coverage reporting (and gcov2lcov tool)

---

tools/sgprotocgengoaiptest/tools.go

Bumps protoc-gen-go-aip-test to 0.14.2

Bump gen-go-aip-test

---

tools/sgprotocgengoaiptest/tools.go

https://github.com/einride/protoc-gen-go-aip-test/releases/tag/v0.15.0

Update to protoc-gen-go-aip-test 0.15.0

---

tools/sgprotocgengoaiptest/tools.go

https://github.com/einride/protoc-gen-go-aip-test/releases/tag/v0.15.1

Update to protoc-gen-go-aip-test 0.15.1

---

tools/sggolines/tools.go

https://github.com/segmentio/golines

Add golines

---

actions/setup/action.yml

chore(actions): use Go 1.22 for setup-sage by default

---

tools/sgprotocgengoaiptest/tools.go

- Releases: https://github.com/einride/protoc-gen-go-aip-test/releases
- Significant change I would like to get in: https://github.com/einride/protoc-gen-go-aip-test/pull/238

Bump to latest protoc-gen-go-aip-test

---

tools/sgapilinter/tools.go
tools/sgbuf/tools.go

- feat(api-linter): bump to v1.66.2
- feat(buf): bump to v1.34.0

minor bumps

---

tools/sgcloudrun/config.go

Add a new LocalDevelop target which runs a cloud run service
locally using an impersonated service account which gives the benfit of
using short-lived tokens for better security and avoids having to refer
to a service account key.
This deprecates the old targets as the new ones are essentially a
better, more secure, replacement.

feat(sgcloudrun): add LocalDevelop target and corresponding command

---

tools/sgprotocgengoaiptest/tools.go

https://github.com/einride/protoc-gen-go-aip-test/pull/253

feat(protoc-gen-go-aip-test): bump to v0.24.1

---

tools/sgbalenacli/tools.go

- **fix(sage): remove usage of locally installed balena binary**
- **feat(balenacli): bump to version v18.2.34**

fix(sgbalenacli): remove balena local override and bump

---

tools/sggolangcilint/tools.go

Fixes G115 (int overflow) false positives

feat: tools/golangci-lint v1.60.3

---

.github/dependabot.yml
tools/sgcspevaluatorcli/package.json
tools/sgcspevaluatorcli/tools.go

Add [csp-evaluator-cli](https://github.com/einride/csp-evaluator-cli) tool

feat(tools): add csp-evaluator-cli

---

tools/sgcloudrun/config.go

to support SA impersonation with debuggers in IDEs

feat(sgcloudrun): add LocalDevelopEnv and CleanUpLocalDevelop

---

tools/sgprotocgengoaiptest/tools.go

Changes https://github.com/einride/protoc-gen-go-aip-test/compare/v0.28.0...v0.30.0

feat(sgprotocgengoaiptest): bump to v0.30.0

---

tools/sggolangcilint/golangci.yml

https://github.com/go-simpler/sloglint

feat(sggolangcilint): add slog linter

---

tools/sgprotocgengoaiptest/tools.go

https://github.com/einride/protoc-gen-go-aip-test/releases/tag/v0.30.1

feat(sgprotocgengoaiptest): bump to v0.30.1

---

tools/sggofumpt/tools.go

https://github.com/mvdan/gofumpt/releases/tag/v0.7.0

feat(gofumpt): bump to version 0.7.0

---

tools/sgprotocgengoaiptest/tools.go

https://github.com/einride/protoc-gen-go-aip-test/releases/tag/v0.31.0

feat(sgprotocgengoaiptest): bump to v0.31.0

---

tools/sggolangcilint/tools.go

https://github.com/golangci/golangci-lint/releases/tag/v1.64.7

fix(golangcilint): bump to v1.64.7

---

tools/sggolangcilintv2/tools.go

https://github.com/golangci/golangci-lint/releases/tag/v2.1.5

feat(sggolangcilintv2): bump to v2.1.5

---

tools/sgshellcheck/tools.go

https://github.com/koalaman/shellcheck/releases/tag/v0.10.0
Changes:
https://github.com/koalaman/shellcheck/compare/v0.9.0...v0.10.0

feat(shellcheck): bump to v0.10.0
