einride/sage

.mage/tools.mk
mgtool/configuration.go

Instead of creating `.tools` in every folder we run mage from, we store everything in the git root directory

fix: use git root dir for .tools

---

.mage/tools.mk
mgtool/configuration.go

After closer debugging, and talking with the mage developers. We get the unwanted logging because the global is set up before logging is configured.

fix(mgtool): use exec.command to solve unwanted logging from global

---

mgtool/configuration.go

The previous PR did not fail, because technically it did download dependencies to a folder, not the expected one though. Needed to do some string formatting, tested locally and tools now ends up in the correct dir

fix(mgtool): format git root path string to get correct path

---

.github/workflows/release.yml
.mage/magefile.go

Part of removing build-time dependency on Node.js for Go projects.

ci: migrate to go-semantic-release

---

targets/mggolangcilint/golangci.yml

- feat(golangci-lint): deprecate golang.org/x/xerrors
- feat(golangci-lint): don't enforce t.Parallel()

feat: update lint rules

---

targets/mggolangcilint/golangci.yml

this linter has a bit too many false positives where the assetion has
been checked beforehand. Let's remove it for now and re-add it for a
stricter linter in the future.

feat(golangcilint): disable `forcetypeassert` linter

---

tools/mgclangformat/targets.go
tools/mgcommitlint/targets.go
tools/mgprettier/targets.go
tools/mgsemanticrelease/targets.go

I was changing this command not to print to standard out, but then I figured this error is kinda overrated. We dont do sanity checks like this on other tools. Just let the system handle it and error out on the install command.

fix: remove npm check

---

mgpath/path.go
tools/mgclangformat/tools.go

Conventionally helper methods always panic and don't return errors.

feat(mgpath): panic if finding files fails

---

.mage/magefile.go
cmd/build/main.go
example/.mage/magefile.go
main.go
tools/mgclangformat/tools.go
tools/mggit/tools.go
tools/mggo/tools.go
tools/mggolangcilint/tools.go
tools/mggolangmigrate/tools.go
tools/mggooglecloudprotoscrubber/tools.go
tools/mgmarkdownfmt/tools.go

- feat: rename mggitverifynodiff to mggit
- feat(mggo): reduce API surface
- feat(mggolangcilint): rename LintCommand to RunCommand
- feat(mgclangformat): make FormatProtoCommand accept ...args
- feat(mggolangmigrate): remove MigrateCommand shorthand
- feat(mggooglecloudprotoscrubber): remove ScrubCommand
- chore(mgmarkdownfmt): fix naming

Reduce API surface and rely more on *exec.Cmd API

---

example/.mage/magefile.go
tools/mgyamlfmt/tools.go

It was previously sitting unused.

fix(example): use the yaml formatter

---

tools/mgclangformat/tools.go

much faster and removes the middle-man.

feat(clangformat): use binary instead of npm

---

mgtool/exec.go
tools/mgbalenacli/tools.go
tools/mggit/tools.go

Allows you to execute arbitrary commands using the 'balena' tool.
Also added a `Output` and `MustOutput` to mgtool. These functions makes it very easy to run git commands and retrieve the output immediately. Easy to run e.g. "git describe --tags" or similar and store the output in a string.

feat(mgbalenacli): add balena-cli tool

---

cmd/init/example/.mage/magefile.go

Github (and I think the industry at large?) is still using master as the default branch name for new repos so it makes more sense to generate 
magefile for master rather than main until this has been changed.

feat: change generated magefile to use master instead of main

---

mgtool/build.go

Often the purpose for wanting to build a Go binary from a remote package using the local go.mod file is so that we build the binary based on the same version as the local repo depends on however we don't want the local go.mod to include dependencies only needed to build that binary (which may be different than the "library" part of the remote repo) so we use the version specified in the local go.mod file but build the binary in module-aware mode so it brings its own dependencies

feat: use module-aware mode when building Go from local mod file

---

mgtool/file.go

`os.Stat` follows symlinks when the intention here is to check whether the symlink exists and remove it if it does. For that we need to use os.Lstat which does not follow symlinks

fix: use os.Lstat instead of os.Stat for symlinks

---

doc.go

Go requires `main` packages to have a main method which we do not. This
causes go tooling to not work when running for example `go get
go.einride.tech/mage-tools` to upgrade to latest mage-tools version

fix: change main package name to magetools

---

tools/sgterraform/tools.go

It is unclear to me whether the `PrepareCommand(context.Context)` function fulfills any purpuse that is not clear in the API (Does not seem to be used anywhere so why is it public? Do we intend for users to be able to use it directly?) so I kept it here for consistency with the other packages.

feat: introduce terraform tool

---

tools/sgshfmt/tools.go

shfmt can format bash scripts to keep them up to date.

feat: shfmt support added

---

Makefile
sg/makefile.go

This reverts commit 97aafa06a99fab1e849bb300c411a7c463339e65.
As @viktorvoltaire pointed out, if we clean at the `.mage` level, we
will "clean" away any work-in-progress sagefiles - that would not be
good!

fix: revert "fix: cleanup the clean target"

---

tools/sgterraform/tools.go

This would be called with something like:
```golang
func (Terraform) CommentOnPullRequestWithPlan(ctx context.Context, pr, project string) error {
cmd = sgterraform.CommentOnPullRequestWithPlan(ctx, pr, project, sgpath.FromGitRoot(filepath.Join(terraformDir, "terraform.plan"))
cmd.Dir = sgpath.FromGitRoot(terraformDir)
return cmd.Run()
}
```

add tf pr comment command

---

.sage/.gitignore
Makefile
example/.gitignore
sg/generate.go
sg/makefile.go
sg/path.go
tools/sggo/tools.go

For build artifacts, such as test coverage reports and similar outputs
from running a build.

feat: introduce build/ dir

---

sg/deps.go
sg/fn.go

Regression from the mage-tools migration, fixed by introducing a unique
ID different from the display name.

fix: ensure unique IDs for functions with different args

---

tools/sggit/tools.go

The short hash is enough to derive the commit

feat(sggit): use short hash when deriving version

---

sg/initfile.go

the first expected argument is the context, and that isn't provided
as an application argument hence the minus one.

fix(init): expected number of arguments

---

sg/initfile.go

in the generated code. Produces correct error output in certain scenarios.

fix: correctly use `fatalf` instead of `fatal`

---

sg/exec.go

Leading whitespace is causing some linter's file references to not get
picked up by GitHub - such as Hadolint.

fix: trim space for command output lines

---

main.go

Nested invocation of sage causes double log tags. :)

fix: prevent double-tagged logs

---

sg/initfile.go

From 
```
[terraform:terraform-plan-dev] No changes. Your infrastructure matches the configuration.
```
To
```
[terraform-plan-dev] No changes. Your infrastructure matches the configuration.
```

feat remove namespace from logger

---

Makefile
sg/generate.go
sg/makefile.go

When migrating to sage in a repository yesterday I found that quite a lot of time I would go back into the sage directory to regenerate my Makefile. Adding a target for doing this could be useful.

feat: add target for building sage

---

tools/sggolangcilint/tools.go

Excludes certain results from the running golangcilint in .sage. Whats good is that this does not interfere with the anyone passing their own `--exclude` as args

exclude results from sage folder

---

sg/deps.go
sg/fn.go
sg/makefile.go

To add more specificity to the vocabulary (borrowing from Make
terminology) - it's hard to be specific when talking about "functions" -
it's easier to be specific when saying "Sage Targets" - because then you
know you are talking about a function that is meant to be run as a
target.

feat: rename sg.Function to sg.Target

---

tools/sggo/tools.go

This adds an explanation for the command and breaks out the
PrepareCommand parts of the command.

chore(sggo): add explanation for the TestCommand

---

tools/sgnpmlicense/tools.go

Add a npm package license checker for frontend projects.
(I started writing my own license checker in Go but it's very much none-trivial to cover all edge cases)

feat(npm-license): add a license-checker for npm

---

tools/sggolangmigrate/tools.go

Building golang migrate requires some extra flags in order to include the spanner drivers so the current one is broken and besides that there is no reason to build it from Go since we don't have any dependencies on the library at runtime and it is generally faster to use the binary

fix: use golang-migrate binary instead of go built version

---

.sage/sagefile.go
Makefile
example/.sage/sagefile.go

The specific linter may not be the same, but we'll still want to run a
standard Go linter.

feat: rename golangci-lint target to go-lint

---

tools/sggrpcjava/tools.go
tools/sgprotoc/tools.go

This makes sure we download the x86 versions of the tools instead
of trying to download the missing arm64 versions.
For this to work it assumes that you have Rosetta 2 running.

feat(protoc): support darwin/m1 for protoc

---

sg/logger.go

When using a namespaced function gets called with `sg.Deps` the namespace gets added to the logger name. 
before:
```
[terraform-terraform-plan] planning terraform..
```
after:
```
[terraform-plan] planning terraform..
```

fix(sglogger): remove namespace from logger name

---

tools/sggit/tools.go

In the driver-app we generate tags with `git describe --tags --long --always`, so would be useful to expose git as a command to follow the same pattern as the other.
And we are using `sggit.VerifyNoDiff` and would like to not have mix of `sggit` and `sg.Command(ctx, "git", ...)`

feat(sggit): expose git as a command

---

Makefile
sg/generate.go
sg/makefile.go

Purpose:
Remove a go dependency for every build step in cloud build. 
Description:
With the 'old' setup, sage will require a dependency on 'go' for every buildstep in cloud-build. This gives more complexities than needed. Every non-go buildstep will need a image with both the desired language as well as go, as sage depends on this. For example if you want to build something with the node could-builder image, it will fail as it has a dependency on go. 
Solution:
The updated state will allow for non-go applications to first call `make sage` with a go based cloud-builder image, which will generate the binary sage file. And subsequently build the app with the desired default type of building images.

feat: remove go dependency for every build step

---

tools/sggcloud/tools.go

This introduces a replacement for handling auth in the actions pipeline, rather then having the below, one can now just use this function and pass the returned json file in the context with `sg.ContextWithEnv` to what ever command that needs it.
```yaml
- id: 'auth'
name: 'GCP Auth'
uses: 'google-github-actions/auth@v0'
with:
workload_identity_provider: 'projects/PROJECT_NR/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
service_account: 'someServiceAccount@...'
```

feat(sggcloud): add GHA WIF auth helper

---

sgtool/file.go
tools/sgclangformat/tools.go
tools/sgconvco/tools.go
tools/sggosemanticrelease/tools.go
tools/sggrpcjava/tools.go
tools/sgprotoc/tools.go
tools/sgprotocgengogrpc/tools.go

- fix: mac m1 support for protocgengogrpc
- refactor: "darwin" string to constant

Mac M1 support for protoc-gen-go-grpc 

---

README.md
sg/initfile.go

I was trying to design a reusable namespace with sage and thought this might be something interesting to support.
The idea is to be able to do something like this
```go
package main
import "fmt"
type MyNamespace struct {
sg.Namespace
Name string
}
func (m MyNamespace) All(ctx context.Context) error {
sg.SerialDeps(
ctx,
m.PrintName,
)
return nil
}
func (n MyNamespace) PrintName(ctx context.Context) error {
fmt.Println(n.Name)
}
```
And then we can reuse the namespace to generate different makefiles
```go
func main() {
sg.GenerateMakefiles(
sg.Makefile{
Path:          sg.FromGitRoot("Makefile"),
DefaultTarget: All,
},
name1 := MyNamespace{Name: "name1"}
sg.Makefile{
Path:          sg.FromGitRoot("names/name1/Makefile"),
DefaultTarget: name1.All,
Namespace:     name1,
},
name2 := …
```

feat: add support for namespace embedding

---

README.md
sg/generate.go
sg/initfile.go

This PR partially fixes what was introduced in https://github.com/einride/sage/pull/198
I decided only to reflect String, Int and Bool. As any other types gets very hard and complex to template, I think these are fine to start with anyway and we can see where this feature takes us

fix(embedded-ns): reflect on values in embedded namesapce

---

sgtool/file.go

To not get links like: [https://github.com/convco/convco/releases/download/v0.3.8/convco-ubuntu.zip...](https://github.com/convco/convco/releases/download/v0.3.8/convco-ubuntu.zip...)

fix(sgtool): add space between url and dots to make it clickable

---

sg/initfile.go
sg/makefile.go

When one function was not eligible for generation, it was preventing all other functions from being evaluated in the package and namespaces.
The bool return wasn't doing much so instead we just run the function

fix: run target generation function for all functions

---

tools/sgapilinter/tools.go

Works consistently regardless of which working dir it's called from.

fix(api-linter): walk from git root instead of cwd

---

sg/makefile.go

Otherwise arguments containing spaces will count each word inside as an
argument

fix: wrap makefile target arguments in quotes

---

Makefile
sg/makefile.go

https://www.gnu.org/software/make/manual/make.html#index-MAKE
> Recursive make commands should always use the variable MAKE, not the
> explicit command name ‘make’, as shown here:
```
subsystem:
cd subdir && $(MAKE)
```

fix: use $(MAKE) for recursive make

---

tools/sggoreview/tools.go

Removes a deprecated invocation of `strings.Title` and upgrades goreview which depended on an old version of golang.org/x/tools which doesn't work properly in > Go 1.18

fix(goreview): upgrade to v0.20.0 in order to support Go 1.18

---

tools/sgsqlc/tools.go

SQLC is a code generator that generate static Go structs from SQL queries. This ensures both performance and type safety for SQL, in addition to a single source of truth (operations are defined in SQL only).
https://github.com/kyleconroy/sqlc

Feat / Add sqlc tool

---

tools/sggolangcilint/tools.go

https://github.com/golangci/golangci-lint/releases/tag/v1.45.1
Includes automatic detection of Go version for example.

fix(golangci-lint): bump to v1.45.1

---

tools/sgconvco/tools.go

This reverts commit 44023c709b2ce6efc92f06326296037c5bb0989f.
Not statically linked against glibc dependency causes errors on Google
Cloud Build.

Revert "feat(deps): bump convco to 0.3.9"

---

tools/sggolangcilint/tools.go

Expose the default golangci-lint config to be used by other projects who want to run the `Command()` but still want to benefit from the defaul configuration.

feat(golangci-lint): expose default config

---

tools/sgapilinter/tools.go
tools/sgbuf/tools.go
tools/sggh/tools.go
tools/sggolangcilint/tools.go

- feat(buf): bump to v1.3.1
- feat(api-linter): bump to v1.30.1
- feat(gh): bump to v2.7.0
- feat(golangci-lint): bump to v1.45.2

bump versions w13

---

tools/sggoreview/tools.go

this should solve some type issues when running go 1.18 in certain repos.

fix(goreview): bump to v0.22.1

---

tools/sgsqlfluff/tools.go

Suggestion to add `sqlfluff` (https://docs.sqlfluff.com/en/stable/) to tools. Formatter (`sqlfluff fix`) and linter (`sqlfluff lint`) for SQL with support for BigQuery, Jinja and dbt.

feat: add sqlfluff tool

---

tools/sgtfsec/tools.go

tfsec uses static analysis of your terraform code
to spot potential misconfigurations.
Rated *Adopt* by Thoughtworks tech radar.

feat: add tfsec tool

---

sgtool/file.go
tools/sggrpcjava/tools.go
tools/sgprotoc/tools.go
tools/sgsqlc/tools.go

Allows running sqlc on ARM64 Mac using Rosetta.

feat(sqlc): fallback to x86_64 builds on Darwin ARM64

---

tools/sgterraform/tools.go

No breaking changes: https://github.com/hashicorp/terraform/blob/v1.2/CHANGELOG.md
The most exciting parts to me are:
- When showing a plan, Terraform CLI will now only show "Changes outside of Terraform" if they relate to resources and resource attributes that contributed to the changes Terraform is proposing to make.
- replace_triggered_by is a new lifecycle argument for managed resources which triggers replacement of an object based on changes to an upstream dependency.

chore(deps): bump terraform from 1.1.4 to 1.2.1

---

tools/sgsemanticrelease/tools.go

github and release-notes-generator plugins are included in the semantic-release package.

feat(sgsemanticrelease): bump semantic-release to 17.0.3

---

tools/sgfirebasetools/tool.go

Expose the `Command` function for using the firebase tool CLI. This PR also includes a `DeployPreview` function for convenient deployments to a preview channel that can be used like this:
```
url, err := sgfirebasetools.DeployPreview(ctx, sgfirebasetools.DeployPreviewOptions{
Project:   "my-gcp-project",
Site:      "my-firebase-site",
CmdDir:    sg.FromGitRoot("frontend"),
ChannelID: "my cool preview",
})
```
All cred goes to @ericwenn for the initial implementation! 🙌

feat: add firebase tool command including preview channels support

---

Makefile
sg/makefile.go

This enables Sage to run in build environments where Go is not installed
by default - for example the `node` image.

feat: increase portability by bootstrapping Go

---

tools/sgcloudendpoints/Dockerfile
tools/sgcloudendpoints/deprecated.go
tools/sgcloudendpoints/tools.go

Split the DockerImage helper into the more composable DeployConfig and
BuildImage helpers.
No longer assume that the Artifact Registry is called `docker`.

feat(sgcloudendpoints): improve helpers

---

tools/sgfirebasetools/tool.go

By default firebase sets the expiry of a channel to 7 days.
In projects with a lot of activity this can lead to the quota of
channels (50) to be hit, preventing all furhter deployments.
By setting a quicker expiration this can be avoided.

feat(sgfirebasetools): add option for channel expiration

---

tools/sgcloudendpoints/deploy.go
tools/sgcloudendpoints/validate.go

Streamlined helpers for our most common use case of deploying an
endpoints gateway from a Buf module and a YAML config.

feat(sgcloudendpoints): add Deploy and Validate helpers

---

tools/sgdbt/tools.go

If approved, this PR will:
- Update the dbt version of the sage dbt tool to `1.2.0`
Current version, `1.0.0`, does not support Python 3.10 - which newer versions of linux distributions such as ubuntu has installed by default.

feat(sgdbt): bump dbt to 1.2.0

---

tools/sgshellcheck/tools.go

Decompressing using xz is not enough, we also need to extract the tarball.

fix(sgshellcheck): untar local archive

---

tools/sggolangcilint/golangci.yml

These three linters have been replaced by "unused" according to the deprecation notice. They have been abandoned by their owners it seems.

fix(golangcilint): removed deprecated linters

---

Makefile
sg/makefile.go

If the local environment does not explicitly set GOWORK=on then we disable go.work support to avoid issues with multi-module repos that are not meant to keep the different modules in sync

feat: disable go.work support if not explicitly set

---

actions/setup/action.yml

to avoid cache is used when go version gets updated.
An example issue we have is build like this failed on master
https://github.com/einride/vehicle-service/actions/runs/3052245767/jobs/4921413170
but works on PR build (which sage get pulled)
The issue, seeing from the log, that on master build the cache is used, but as we recently updated go version, the generated files changed format so on master build we will have to update cache as well (or we need to manually call `make clea-sage` each time for the master build, I suppose...?)
If this `${{ inputs.go-version }}` can get evaluated correctly, I think it can unblock our master build filling issue.

feat: update cache if go version changed

---

tools/sgapilinter/tools.go
tools/sgbuf/tools.go
tools/sggh/tools.go
tools/sggolangmigrate/tools.go
tools/sgprotoc/tools.go
tools/sgprotocgengoaiptest/tools.go
tools/sgprotocgengogrpcserviceconfig/tools.go
tools/sgterraform/tools.go
tools/sgtfsec/tools.go
tools/sgyq/tools.go

- feat(api-linter): bump to 1.36.0
- feat(buf): bump to 1.8.0
- feat(gh): bump to 2.15.0
- feat(golang-migrate): bump to 4.15.2
- feat(protoc): bump to 3.19.5
- feat(protoc-gen-go-aip-test): bump to 0.8.1
- feat(protoc-gen-go-grpc-service-config): bump to 0.6.0
- feat(terraform): bump to 1.2.9
- feat(tfsec): bump to 1.27.6
- feat(yq): bump to 4.27.5

feat: bump tool versions (sep 2022)

---

tools/sgapilinter/tools.go

Version 1.36.0 does not have any binaries uploaded to it on GitHub
releases.

feat(api-linter): downgrade to 1.35.1

---

.sage/sagefile.go
Makefile
example/.sage/sagefile.go
tools/sgyamlfmt/tools.go
tools/sgyamlfmt/yamlfmt.yaml

this deprecates `github.com/einride/yamlfmt` in favor of
`github.com/google/yamlfmt`
A reason for this is its support of retaining line breaks when
formatting

feat(yamlfmt): add `google/yamlfmt` over `einride/yamlfmt`

---

tools/sgconvco/tools.go

Update to new version https://github.com/convco/convco/releases/tag/v0.3.12
`--ignore-reverts` is introduced with the new version and if people want they can turn it on for their backend service so those Github `Revert` button generated message will be ignored by convco check.
Noticing a side effect is the changelogs will also miss this `Revert "some last commit message"` as well. But I guess for backend services the changelogs are not that important so perhaps it is fine.

chore(convco): update to version 0.3.12

---

tools/sggit/tools.go

Splitting a string always returns at least one element - when there are
no tags we handle the special case to return an empty result.

fix(sggit): handle missing tags correctly

---

tools/sggolangcilint/golangci.yml

There seem to be race conditions between linters and fixers when running in parallel.
Prefer finding as many lint errors as possible, as opposed to convenience of auto fixing.

fix(golangcilint): disable auto fixing

---

tools/sggolangcilint/tools.go

The default Run() doesn't always work in monorepos with multiple go.mod
files, including in the root and in subfolders.
This changes makes it possible to specify a subdirectory to run in,
reusing the default config if possible, while keeping the existing
behavior of Run().

feat(sggolangcilint): possibility to run in a single directory

---

tools/sgterraform/tools.go

This upgrades terraform to the latest version (v1.3.2).
Looking through the release notes there is nothing that breaks how sage is using terraform.
The main thing that it introduces is two new string functions: `startswith` and `endswith` that will be very useful, especially for variable validation.
The full release notes can be found below:
- [v1.3.2](https://github.com/hashicorp/terraform/releases/tag/v1.3.2)
- [v1.3.1](https://github.com/hashicorp/terraform/releases/tag/v1.3.1)
- [v1.3.0](https://github.com/hashicorp/terraform/releases/tag/v1.3.0)

feat(terraform): bump to v1.3.2

---

tools/sgsqlc/tools.go

In sqlc v1.15.0 they have introduced the concept of nullable enum types.
Full release notes can be found [here](https://github.com/kyleconroy/sqlc/releases/tag/v1.15.0)

feat(sqlc): bump to v1.15.0

---

tools/sgdbt/tools.go

If approved this PR will:
Bump the version of dbt-bigquery 1.2.0 --> 1.3.0
[Full change log found here](https://github.com/dbt-labs/dbt-bigquery/releases/tag/v1.3.0)

chore(dbt): bump dbt-bigquery version 1.2.0 -> 1.3.0

---

tools/sggolangcilint/tools.go

Got segmentation fault error with version 1.50, but works with 1.50.1.
```
[go-lint] running...                                                                                                                                                                                              
[go-lint] signal: segmentation fault                                                                                                                                                                              
make: *** [sage.mk:80: go-lint] Error 1  
```

feat(sggolangcilint): bump to version 1.50.1

---

tools/sgphrase/tools.go

The binary name inside the tar ball for macosx and linux is different. Download and rename the binary instead.

fix(sgphrase): download binary instead of tar ball

---

actions/setup/action.yml

This reverts commit e443bb44aea63957b34a37474e1ec44dadaa2fc2.
Specifying a branch, or defaulting to master, makes PR tests run on the latest commit on that branch, not on the PR commit.

revert(actions): add input to checkout different branch than default

---

tools/sgapilinter/tools.go

Here are the release notes: https://github.com/googleapis/api-linter/releases/tag/v1.37.0

feat: update api-linter to v1.37.0

---

tools/sgcloudsqlproxy/tool.go

<div data-pjax="true" data-test-selector="body-content" data-view-component="true" class="markdown-body my-3"><h2><a href="https://github.com/GoogleCloudPlatform/cloud-sql-proxy/compare/v1.33.0...v1.33.1">1.33.1</a> (2022-11-15)</h2>
<h3>Bug Fixes</h3>
<ul>
<li>update dependencies to latest versions (<a href="https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1546" data-hovercard-type="pull_request" data-hovercard-url="/GoogleCloudPlatform/cloud-sql-proxy/pull/1546/hovercard">#1546</a>) (<a href="https://github.com/GoogleCloudPlatform/cloud-sql-proxy/commit/a3aba9a2552831b5aa1935af9a4ef4371d30a37c">a3aba9a</a>)</li>
</ul>
</div>
<div data-pjax="true" data-test-selector="body-content" data-view-component="true" class="markdown-body my-3"><h2><a …

feat(sgcloudsqlproxy): bump to v1.33.1

---

actions/setup/action.yml

https://github.com/actions/runner/issues/1483
https://github.com/actions/runner/issues/1483#issuecomment-1279933184
---
I've noticed that several CI jobs have been pretty slow recently and most repositories have empty caches (e.g., pick any repository, go to **Actions** -> **Caches**)
Example log when running the composite setup sage action,
Currently (no `actions/cache@v3` log row):
After this change:

fix(gha-actions): evaluate composite input bool as string

---

sg/logger.go

This PR is maybe a bit controversial, so I am happy to close it if it is disliked 😅 
This partly reverts 760385e3556f65800ed1bfb9b3642be12b39d923, but adds the namespace in the prefix separated by a colon.
Examples:
- behavior with this commit:
`[service:go-lint] linting Go files...`
- behavior before this commit:
`[go-lint] linting Go files...`
- behavior before 760385e3556f65800ed1bfb9b3642be12b39d923
`[service-go-lint] linting Go files...`
This could be useful when running a lot of targets in different namespaces in parallel, e.g. a CI pipeline running `go-lint` in multiple services concurrently, to know which namespace the log line relates to.

feat(sglogger): add namespace prefix to logger

---

tools/sgnpmlicense/tools.go

The csv format outputs one row per dependency. The list of all
dependencies (incl. transitive) in most projects is huge, which means
this command spits out hundreds of lines even when everything is fine.
The summary format is at least limited to the number of used licenses in
project dependencies (~10-20).

fix(sgnpmlicense): output summary instead of csv

---

tools/sgmvn/tools.go

3.8.6 is inaccessible and therefore the optimizer core builds fail, like this one: https://console.cloud.google.com/cloud-build/builds/95c4a640-10c9-4d4f-9d60-40f9f3f6ac7a?project=einride-vrp-optimizer-core

chore(sgmvn): bump mvn from 3.8.6 to 3.8.7

---

tools/sggolangcilint/tools.go

Adds support for Go 1.20 among other things.
https://github.com/golangci/golangci-lint/releases/tag/v1.51.0

feat(golangcilint): bump to v1.51.0

---

tools/sggolangcilint/tools.go

Minor fix version. Changelog can be found here:
https://github.com/golangci/golangci-lint/releases/tag/v1.51.1

fix(golangcilint): bump to v1.51.0

---

tools/sggolicenses/tools.go

In projects where there are no Go files in the same folder as the go.mod file (often because one wants to keep the go.mod in the root of the project to keep git tagging simple) the license checker fails as it expects go source files where it is running.
So we add a new CheckInDirectory target which uses a specified directory instead of a go.mod file

feat(sggolicenses): add command for checking license in a specific path

---

tools/sgapilinter/tools.go
tools/sgbuf/tools.go
tools/sggolangcilint/tools.go

- feat(buf): bump to 1.14.0
- feat(api-linter): bump to 1.42.0
- feat(golangci-lint): bump to v1.51.2

bump versions feb 2023

---

tools/sgdbt/tools.go
tools/sgsqlfluff/tools.go

if approved, this PR will:
- Upgrade dbt core to `1.4.0`.
- Remove the temporary workaround where `pytz` is explicitly installed. Not needed anymore as this is fixed in dbt core https://github.com/dbt-labs/dbt-core/pull/7077

fix: upgrade dbt-core to 1.4.0

---

tools/sgsqlfluff/tools.go

Fixes a problem fixed in https://github.com/sqlfluff/sqlfluff/pull/4317
causing all sqlfluff runs to fail due to the same fix pushed here
https://github.com/einride/sage/pull/399/files

chore: bump sqlfluff from 1.4.5 to 2.0.0a4

---

tools/sgko/tools.go

Changelog can be found here:
https://github.com/ko-build/ko/releases/tag/v0.13.0

fix(ko): bump to v0.13.0

---

tools/sgprotoc/tools.go

Recently, a fix was merged (https://github.com/einride/sage/pull/401) to use arm64 binaries when available. In protobuf v3.19.5, the binary for OSX arm64 is not available (see [here](https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.5)), and any command using protoc fails when run locally. It does exisit in the [latest release](https://github.com/protocolbuffers/protobuf/releases/tag/v22.2), so bumping the version should fix the issue.
If approved, this PR will:
- Bump protobuf version from v3.19.5 to v22.2
Open to alternative fix suggestions.

fix(protoc): bump to v22.2

---

actions/setup/action.yml

Workflows using the setup-sage action will now default to Go 1.20 instead of Go 1.19.

feat(actions): default to Go 1.20

---

tools/sgmvn/tools.go

archive.apache.org is a long-term archive, whereas dlcdn.apache.org has a limited selection of latest
releases. After 3.8.8 was released, 3.8.7 was removed from the latter server.

fix(sgmvn): change remote for downloading mvn

---

tools/sggolangcilint/tools.go

Minor fixes:
https://github.com/golangci/golangci-lint/releases/tag/v1.52.1

fix(golangcilint): bump to v1.52.1

---

tools/sggolangcilint/tools.go

Minor fix:
https://github.com/golangci/golangci-lint/releases/tag/v1.52.2

fix(golangcilint): bump to v1.52.2

---

Makefile
sg/makefile.go

Same version as the github action uses

feat: bump default Go version to 1.20.2

---

tools/sggolangcilint/golangci.yml

The word cancelled is spelled differently between GB English and US English.
The Google API linter specifically chooses the GB spelling and this causes issues
when both linters are used together, which is the vast majority of Einride services.
An example of this contradiction is shown below:
```
--- API LINTER
example.proto:1:5: Prefer "CANCELLED" over "CANCELED" for state names (core::0216::value-synonyms)
...
--- MISSPELL
example_test.go:1:59: `CANCELLED` is a misspelling of `CANCELED` (misspell)
```
We have the option to configure this on the misspell linter so it makes the most
sense to do the change there.

feat: ignore words with contradictory spellings

---

tools/sggosemanticrelease/tools.go

Make it possible to pass additional command line arguments
to the `semantic-release` command.

feat(semantic-release): add optional arguments

---

tools/sggosemanticrelease/tools.go

https://github.com/go-semantic-release/semantic-release/releases/tag/v2.27.1

feat(gosemanticrelease): bump to v2.27.1

---

actions/setup/action.yml

Since v4 of setup-go, caching of the root go module is enabled by default. This means we are caching the modules twice and also causing some conflict on restore.
Removing our caching of Go modules should hopefully fix this.

fix(actions): delegate cache to setup-go action

---

actions/setup/action.yml

If there is a cache miss, we now walk up the tree until we find a hit. Even if the hit is not a perfect match, it is at least (probably...) better than a cache miss.
Since this uses a new cache key, it will be a cache miss the first time after this change is merged.

fix(cache): hierarchically restore Sage cache

---

tools/sgcloudsqlproxy/tool.go

Beaking change as one will need to replace the cmd parameter from
'cloud_sql_proxy -instances=myproject:myregion:myinstance=tcp:5432 --enable_iam_login'
to:
'cloud-sql-proxy myproject:myregion:myinstance --port 5432 --auto-iam-authn'
---
Perhaps this can help the build error that shows up recently from time to time?
```
[backend:deploy-dev] migrating database...
[backend:deploy-dev] 2023/06/16 08:31:09 current FDs rlimit set to 65536, wanted limit is 8500. Nothing to do here.
[backend:deploy-dev] 2023/06/16 08:31:09 using credential file for authentication; 
[backend:deploy-dev] Running golang migrate...
[backend:deploy-dev] error: dial tcp [::1]:5432: connect: connection refused
[backend:deploy-dev] could not migrate database: exit status 1
```
As this error seems happened in the db …

fix(tools)!: upgreade sgcloudsqlproxy to 2.3.0 (breaking change) 

---

tools/sgsqlfluff/tools.go

SQLFluff 2.1.1 is not compatible with dbt-core 1.5.2 which was released on Thursday. As we only pin dbt-bigquery we download dbt-core 1.5.2 resulting in SQLFluff errors.

fix(sgsqlfluff): pin dbt-core to 1.5.1 in sgsqlfluff

---

tools/sgapilinter/tools.go
tools/sgbalenacli/tools.go
tools/sgbuf/tools.go
tools/sgconvco/tools.go
tools/sggh/tools.go
tools/sggolangmigrate/tools.go
tools/sggoreleaser/tools.go
tools/sgko/tools.go
tools/sgshellcheck/tools.go
tools/sgshfmt/tools.go
tools/sgterraform/tools.go
tools/sgtfsec/tools.go
tools/sgyamlfmt/tools.go
tools/sgyq/tools.go

- feat(deps): bump api-linter to v1.52.3
- feat(deps): bump balena-cli to v16.6.3
- feat(deps): bump buf to v1.23.1
- feat(deps): bump convco to v0.4.0
- feat(deps): bump gh to 2.31.0
- feat(deps): bump golang-migrate to v4.16.2
- feat(deps): bump go-releaser to v1.19.1
- feat(deps): bump ko to v0.14.1
- feat(deps): bump shellcheck to v0.9.0
- feat(deps): bump shfmt to v3.7.0
- feat(deps): bump terraform to v1.5.2
- feat(deps): bump tfsec to v1.28.1
- feat(deps): bump yamlfmt to v0.9.0
- feat(deps): bump yq to v4.34.1

summer of 2023 bump deps

---

tools/sgterraform/tfplan.go
tools/sgterraform/tools.go

Iterated version of the TF plan PR comment functionality created by @alethenorio in the [gcp-projects repo](https://github.com/einride/gcp-projects/blob/master/.sage/cdktf.go#L361). Difference between this and the existing comment functionality is that it shows an overall summary and a list of type of resources being changed grouped by action. See example of output in image below. The full HCL plan is also included but collapsed by default. The tfplan file contains simplified TF json definitions lifted from the [github.com/hashicorp/terraform-json](github.com/hashicorp/terraform-json) repo.

feat(ghcomment): add GH TF comment with summary

---

sg/path.go

Path helpers are typically used in conjuction with writing a file, this
simplifies workflows related to generating build files.
Parent directories are only created automatically by helpers leading
into ignored directories (build, tools, bin).

feat: ensure parent directories in path helpers

---

tools/sgtfsec/tools.go
tools/sgtrivy/tools.go
tools/sgtrivy/trivyignore

tfsec is [deprecated](https://github.com/aquasecurity/tfsec/discussions/1994) and the recommendation is to use trivy where the development will continue.
Trivy does a lot more than just Terraform security checking but this commit is limited to replacing tfsec and includes only one helper command to make the transition easy for `sgtfsec` users (API is slightly different).
`sgtrivy` also includes a default .trivyignore which currently only ignores https://avd.aquasec.com/misconfig/google/storage/avd-gcp-0066/ for being too strict.
Lastly, the sgtfsec package has been marked as deprecated.

feat: add trivy tool

---

main.go

If merged this PR will fix the init command returning the error `.sage: file exists`. This was caused by a recent addition of `ensureParentDir` to `FromBinDir`. The function `sg.Command` uses `FromBinDir` which causes the .sage directory to already be created when `os.Mkdir` is called in `initSage`

fix: init sage in repository not working

---

tools/sgmdformat/tools.go

This is desired to have access to a markdown formatter that can render on both
Github and Backstage.
I have searched for Go based tools but unfortunately couldn't find one that fulfilled the requirements of:
- easy to use
- can recursively format all `.md` files in repo.

feat: add gfm markdown formatter

---

tools/sggolangcilint/tools.go

Ensures compatibility with Go v1.21.

feat(golangcilint): bump to v1.54.1

---

tools/sgtrivy/tools.go

Trivy has mutliple scanners that look for different file formats and tries to scan them. For example there is a kubernetes scanner that will find certain of our generated yaml files and incorrectly interpret them as kubernetes files. Then it will find Kubernetes security issues with those files.
We should in general only be interested in scanning Terraform files. As a way to prevent trivy from scanning other files, we're here using the --skip-files directive. Examples of how to use --skip-files can be found here: https://github.com/aquasecurity/trivy/blob/6f03c79405e7d3f77dac0c70c265d972a63ba629/docs/docs/configuration/skipping.md?plain=1#L18

fix(sgtrivy): do not scan yaml files

---

tools/sgcloudspanner/emulator.go

The emulator [now supports](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/releases/tag/v1.5.9) `ON DELETE CASCADE`. This is needed when bumping [`cloud.google.com/go/spanner` to v1.48.0 or beyond](https://github.com/googleapis/google-cloud-go/releases/tag/spanner%2Fv1.48.0) as it now automatically inserts the default `ON DEFAULT NO ACTION` clause (see https://github.com/googleapis/google-cloud-go/pull/8296).
See example failure in iam-go: https://github.com/einride/iam-go/pull/523

feat(sgcloudspanner): bump from 1.5.0 to 1.5.9

---

tools/sgapilinter/tools.go

Somehow 1.52.4 version causes a segfault in some localized cases. Cannot replicate the segfault on 1.57.1.

feat: bump api-linter to 1.57.1

---

tools/sgapilinter/tools.go

Updates api-linter to version [v1.56.1](https://github.com/googleapis/api-linter/releases/tag/v1.56.1) as v.[1.57.0](https://github.com/googleapis/api-linter/releases/tag/v1.57.0) introduced a new
requirement for (google.api.field_behavior) = IDENTIFIER to be set on
the name field of a proto resource.
There is a conflict between buf lint and api-linter due to an update to
field_behaviour.proto. An issue has been opened buf as fix is on their side:
https://github.com/bufbuild/buf/issues/2474

fix: rollback version update on api-linter

---

tools/sgapilinter/tools.go

The issue referenced in #466 has been resolved so we can update the api-linter version again.

feat: update api-linter version to v1.57.1

---

tools/sgdocker/command.go

Previous when running from a mac with apple silicon you will get routed too:
`https://download.docker.com/mac/static/stable/arm64/...`
With this change it will correctly route too:
`https://download.docker.com/mac/static/stable/aarch64/...`

feat(sgdocker): support apple silicon

---

tools/sgcloudendpoints/tools.go

Go version updated to 1.20 which should fix CVE-2022-27664:
>  In net/http in Go before 1.18.6 and 1.19.x before 1.19.1, attackers can cause a denial of service because an HTTP/2 connection can hang during closing if shutdown were preempted by a fatal error.

feat(cloud-endpoints): bump ESPv2 to 2.46.0

---

tools/sgapilinter/tools.go

Contains fix for AIP-203 panic:
https://github.com/googleapis/api-linter/pull/1282

feat(api-linter): bump to v1.59.1

---

tools/sgcommitlint/tools.go

Dropping support for Node v16 and TypeScript v4.

feat(sgcommitlint): bump commitlint to v18

---

tools/sgprotocgengoaiptest/tools.go

This bump adds generation of AIP delete tests if using protoc-gen-go-aip-test. That means that updating sage to this version can cause build failures in repositories which do not have code that passes the newly generated tests.
If fixing the business code to adhere to the new tests is not an option, one can use the `skip` flag in the test suite config to avoid running the delete tests. See https://github.com/einride/protoc-gen-go-aip-test#skipping-tests for more information on how to do this.

feat(deps): bump protoc-gen-go-aip-test

---

tools/sgcommitlint/tools.go

Seems like 18.3.0 is not available.
I've seen some builds fail silently because of this.
https://www.npmjs.com/package/commitlint?activeTab=versions

Bump commit lint to 18.4.1

---

.sage/main.go
CODE_OF_CONDUCT.md
README.md
example/.sage/main.go
tools/sgmarkdownfmt/tools.go
tools/sgmdformat/tools.go

This changes the default markdown formatter from `markdownfmt` to `mdformat`. The reason to do this is for numerous reasons, the main ones are:
- Better support for GH flavour of markdown, which most users are used to and there are less surprises when formatted and rendered
- Supports reference style links, see issue: https://github.com/shurcooL/markdownfmt/issues/34
- Has support for line wrapping to make md files easier to read in raw format in terminal.
I have also added default arguments to mdformat to make it easier to adopt without having to specify these args yourself but can overwrite them as needed.

feat: switch markdown formatter

---

tools/sgartifactregistry/auth.go

Include NPMAuthenticate target to authenticate towards npm artifact
registries.
We authenticate using both npm and yarn
relates to [TCC-345](https://einride.atlassian.net/browse/TCC-345)
[TCC-345]: https://einride.atlassian.net/browse/TCC-345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add new sgartifactregistry package

---

tools/sgmdformat/tools.go

Previously it was not possible to specify the paths that mdformat should be run against due to the way that the default args were set. This allows either all args to be replaced or use the default thus giving users more control.

fix: allow paths arg to be updated on mdformat

---

tools/sgartifactregistry/auth.go

When using `gcloud auth print-access-token`, gcloud will print the token
regardless on whether the token is expired or not.
We use gcloud to figure out if the token is expired for a better user
experience (instead of the user getting back a 403 which can be
confusing)

feat(sgartifactregistry): determine if access token is expired on npm auth

---

tools/sgtrivy/tools.go

Trivy has added support for specifying configuration scanners so we
bump trivy to the latest version and specify the terraform scanner
in the CheckTerraformCommand

feat(sgtrivy): add proper support for scanning only Terraform files

---

.github/dependabot.yml
tools/sgmdformat/requirements.txt
tools/sgmdformat/tools.go
tools/sgpython/command.go

This tracks Python dependencies in a `requirements.txt` file to easier handle multiple dependencies (likely only mdformat plugins).
Also, add the [admonitions mdformat plugin](https://github.com/KyleKing/mdformat-admon) to support [TechDocs admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonitions).

mdformat: setup dependency file and add admonitions support

---

CODE_OF_CONDUCT.md
tools/sgmdformat/requirements.txt

- With the update of [mdformat-admon](https://github.com/einride/sage/pull/503) ([v2.0.0](https://github.com/KyleKing/mdformat-admon/releases/tag/v2.0.0)), the support for mkdocs admonitions was moved into https://github.com/KyleKing/mdformat-mkdocs.
- Added dependency https://github.com/KyleKing/mdformat-mkdocs.
- Ran `make format-markdown` (added some changes to the code of conduct).
- Slack ref: https://einride.slack.com/archives/C02UQKNJBJL/p1707141026793539
- This was not actually tested on mkdocs admonitions... so, let's just 🤞 
- [GitHub flavoured admonitions](https://github.com/orgs/community/discussions/16925) still don't work as the formatter will break them by injecting escaping backslashes before the brackets.
- @thall noticed that [the mdformat …

feat(mdformat): add mdformat-mkdocs

---

CODE_OF_CONDUCT.md
tools/sgmdformat/requirements.txt

Reverts einride/sage#506
This caused all sorts of havoc. Now `make format-markdown` complains about images that uses space in its caption, like `[foo bar](image.png)` and also it complains about links that are longer than 80 characters.
And all this without even mentioning what's wrong. Example:
```
❯ make format-markdown
[sage] building binary and generating Makefiles...
[format-markdown] formatting Markdown files...
[format-markdown] Error: Could not format
[format-markdown] "/Users/fredrik/code/work/private/book-service/docs/runbooks/managing-cloudsql-maintenance.md".
[format-markdown] 
[format-markdown] The formatted Markdown renders to different HTML than the input Markdown. This
[format-markdown] is likely a bug in mdformat. Please create an issue report here, including the …
```

Revert "feat(mdformat): add mdformat-mkdocs"

---

tools/sgapilinter/tools.go
tools/sgbuf/tools.go
tools/sggh/tools.go
tools/sggolangcilint/tools.go
tools/sggolangmigrate/tools.go
tools/sggoreleaser/tools.go
tools/sggosemanticrelease/tools.go
tools/sggovulncheck/tools.go
tools/sgko/tools.go
tools/sgterraform/tools.go
tools/sgyamlfmt/tools.go

- feat(api-linter): bump to v1.63.6
- feat(buf): bump to v1.29.0
- feat(gh): bump to v2.44.1
- feat(golangci-lint): bump to v1.56.2
- feat(golang-migrate): bump to v4.17.0
- feat(goreleaser): bump to v1.24.0
- feat(go-semantic-release): bump to v2.30.0
- feat(govulncheck): bump to v1.0.4
- feat(ko): bump to v0.15.1
- feat(terraform): bump to v1.7.3
- feat(yamlfmt): bump to v0.11.0

version bumps feb 2024

---

sg/fn.go
sg/fn_test.go

It seems common to pass arguments to Deps and SerialDeps as below:
```go
type namespace sg.Namespace
func (n namespace) Default(ctx context.Context) error {
sg.Deps(ctx, n.FirstTarget, n.SecondTarget)
return nil
}
```
Currently this leads to logs in the dep targets to be prefixed with
`[namespace:first-target-fm]` and `[namespace:second-target-fm]`, because
of how the compiler implements methods bound to specific receivers. If
instead the dependencies were specified as:
```go
sg.Deps(ctx, namespace.FirstTarget, namespace.SecondTarget)
```
the names would log prefixes would simply be `[namespace:first-target]`
and `[namespace:second-target]`.
This commit removes the `-fm` suffix. This is safe as no function name
in go can include a hyphen.

fix(sg): remove -fm suffix in target names

---

tools/sggolangcilint/golangci.yml

This removes goconst following internal discussions. But also adds protogetter: https://github.com/ghostiam/protogetter

Remove goconst, add protogetter

---

tools/sggolangcilint/golangci.fix.yml
tools/sggolangcilint/tools.go

Runs `golangci-lint --fix` with a default fix config which is a subset
of the default lint config, with a few modifications:
* Don't run in parallell (may cause issues between fixers)
* Remove all linters who are not fixers (to speed up invocation)

feat(golangci-lint): add Fix helper

---

.sage/main.go
Makefile
example/.sage/main.go
tools/sggofumpt/tools.go

Runs `golangci-lint --fix` and `golines`.

feat: add go-format example target

---

tools/sgbiome/tools.go

Ideally the binary should be named `biome` rather than `biome-darwin-arm64` to support other platforms

Add biome as a json formatter

---

tools/sggolangcilint/golangci.yml

In `golangci-lint` [v1.57.0](https://github.com/golangci/golangci-lint/releases/tag/v1.57.0) `run.skip-dirs` is replaced by `issues.exclude-dirs`.

chore(golangci-lint): align with updated config options

---

.github/CODEOWNERS
tools/sgapilinter/tools.go
tools/sgbuf/tools.go
tools/sggh/tools.go
tools/sggolangcilint/golangci.yml
tools/sggolangcilint/tools.go
tools/sggoreleaser/tools.go
tools/sgko/tools.go
tools/sgmarkdownfmt/tools.go
tools/sgprotocgengogrpc/tools.go
tools/sgterraform/tools.go
tools/sgtrivy/tools.go

- feat(api-linter): bump to v1.64.0
- feat(buf): bump to v1.30.1
- feat(gh): bump to v2.47.0
- feat(golangci-lint): bump to v1.57.2
- feat(goreleaser): bump to v1.25.1
- feat(ko): bump to v0.15.2
- feat(markdownfmt): mark as deprecated
- feat(protoc-gen-go-grpc): bump to v1.3.0
- feat(terraform): bump to v1.7.5
- feat(trivy): bump to v0.50.1
- chore: remove individuals from CODEOWNERS

bump versions april 2024

---

tools/sgtrivy/tools.go

Trivy has added support for scanning terraform plan snapshots and
thus so updated the config names.
See [PR](https://github.com/aquasecurity/trivy/pull/6176)
Fixes error:
```
[terraform:security-check] 2024-04-09T09:37:47.378Z	INFO	Misconfiguration scanning is enabled
[terraform:security-check] 2024-04-09T09:37:47.378Z	INFO	Need to update the built-in policies
[terraform:security-check] 2024-04-09T09:37:47.378Z	INFO	Downloading the built-in policies...
[terraform:security-check] 46.13 KiB / 46.13 KiB [-----------------------------------------------------------] 100.00% ? p/s 0s
[terraform:security-check] 2024-04-09T09:37:47.570Z	ERROR	Invalid misconfig scanners specified: [terraform terraformplan] defaulting to use all misconfig scanners
[terraform:security-check] 2024-04-09T09:37:50.125Z …
```

fix(sgtrivy): update misconfig-scanners

---

tools/sggovulncheck/tools.go

[Release Notes](https://github.com/golang/vuln/releases/tag/v1.1.0)

feat(sggovulncheck): bump to 1.1.0

---

tools/sgpostgres/local.go

This pr will add a tool 'sgpostgres' tool similar to 'sgspanner' emulator, but then for Postgres. 
On the start of a test run (`make go-test`), sage can spin up a local postgres instance in a docker container. This db instance can be shared between tests, such that not every test needs to spin up a separate database instance. Similar to sgspanner, it posts the address how to connect to the db in an environment property.
For charge-control this will improve test run times by ~40%.

feat(cco-1025): add setup for local test postgres instance to support using a shared test instance

---

tools/sgapilinter/tools.go
tools/sgbuf/tools.go
tools/sgconvco/tools.go
tools/sggh/tools.go
tools/sggolangcilint/tools.go
tools/sggolangmigrate/tools.go
tools/sggoreleaser/tools.go
tools/sggovulncheck/tools.go
tools/sgko/tools.go
tools/sgterraform/tools.go
tools/sgtrivy/tools.go
tools/sgyamlfmt/tools.go

- feat(api-linter): bump to v1.66.1
- feat(buf): bump to v1.33.0
- feat(convco): bump to v0.5.1
- feat(gh): bump to v2.51.0
- feat(golangci-lint): bump to v1.59.1
- feat(golang-migrate): bump to v4.17.1
- feat(goreleaser): bump to v2.0.1
- feat(govulncheck): bump to v1.1.2
- feat(ko): bump to v0.15.4
- feat(terraform): bump to v1.8.5
- feat(trivy): bump to v0.52.1
- feat(yamlfmt): bump to v0.12.1

summer bumping 2024

---

tools/sggolangcilint/golangci.yml

Allow word `analyses` as a plural form of analysis in linter.

fix: allow word analyses for misspell linter

---

sg/deps.go
tools/sggolangcilint/tools.go

Bump Golangci-lint to 1.60.1. 
First version with support for Go 1.23 - [Release Notes](https://github.com/golangci/golangci-lint/releases/tag/v1.60.1)

feat(golangci-lint): bump to 1.60.1, support for go 1.23.0

---

tools/sgapilinter/tools.go

[Release notes](https://github.com/googleapis/api-linter/releases/tag/v1.67.2)

feat(sgapilinter): bump to v1.67.2

---

actions/setup/action.yml

This aims to solve the problem where two caches are uploaded (one by `actions/go-setup` and one by `actions/cache`, but where the one from `actions/go-setup` was created by the fastest workflow (with the least
dependencies) and then often used by the slower/heavier workflows. These heavier workflows reuse the cache but it does not contain all dependencies and so it has to re-download and re-build them on every commit. The cache is not rebuilt because there are additional dependencies downloaded.
TL;DR the wrong cache is being used.
The issue is described in detail here: https://github.com/actions/setup-go/issues/358
- Stop using cache by `actions/go-setup`.
- Extend caching of `actions/cache` so to also cover Go dependencies and builds. Effectively doing what `actions/go-setup` was …

fix: address unreliable go dependency caching

---

actions/setup/action.yml

(unless there is no cache yet, or course)
In #571 we disabled `actions/go-setup`, and delegated all caching to `actions/cache` because we can reliably pass it a cache key.
However, it turns out that there are specific constraints/requirements around caches and branches:
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
Right now, the first commit of a PR doesn't use the cache that was created by another PR. But:
> Workflow runs can restore caches created in either the current branch or the default branch (usually main).
This means we could make sure to have a "master cache" that the PR falls back onto (using a `restore-keys` entry).
- Added an if/elif/else dance, which …

fix: PR cache fallback to master/main branch's cache

---

tools/sggolangcilint/golangci.yml

Checks for common OpenTelemetry mistakes.

feat(golangcilint): enable spancheck linter

---

tools/sggolangcilint/golangci.yml

We currently get the following warning when running the linter:
"The linter 'exportloopref' is deprecated (since v1.60.2) due to:
Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar."

feat(golangcilint): replace exportloopref with copyloopvar

---

tools/sggolangcilint/golangci.yml

feat: tools/golangci-lint disable G115

---

tools/sgprettier/tools.go

Use package prettier-plugin-go-template[1] for *.html and *.tmpl files.
[1]: https://www.npmjs.com/package/prettier-plugin-go-template

feat(prettier): add target to style Go templates

---

tools/sgcspevaluatorcli/csp.go
tools/sgcspevaluatorcli/csp_test.go
tools/sgcspevaluatorcli/tools.go

ContentSecurityPolicy type provides a set of helper functions to define content security policy in a structured way.

feat(sgcspevaluatorcli): add csp helper type

---

sg/exec.go
sg/initfile.go
tools/sgcloudrun/config.go

if two processes run LocalDevelopment command, they should use
different credes.json to avoid conflict.
also adds support for context cancellation when CTRL-C detected.

sgcloudrun: avoid creds.json conflict

---

tools/sgcloudspanner/emulator.go
tools/sggosemanticrelease/tools.go

- feat(go-semantic-release): remove Cloud Build helper
- feat(cloud-spanner): remove special handling of Cloud Build

remove cloud build helper

---

tools/sggolangcilint/tools.go

Before this PR Sage Golangci-Lint would run for all sub folders where a go.mod is found and terminate when the first command returns an errors, could be a lint issue or some other error.
After Golangci-Lint will run for all sub folders and will run for all projects and join all errors together.

GolangCI Lint runs for all targets

---

tools/sgko/tools.go

When looking into container security findings I just noticed there's a newer
version of ko which we might want to use?
https://github.com/ko-build/ko/releases/tag/v0.16.0

feat(ko): bump to 0.16.0

---

tools/sgbuf/tools.go

Let's just keep up to date!
Buf is getting an lsp! 🎉 
- Bump it!
Please note that in v1.40.0 they deprecated the `buf lint` ruleset from `DEFAULT` to `STANDARD`. You'll see this warning:
```
❯ buf lint --verbose
WARN    Category DEFAULT referenced in your buf.yaml is deprecated. It has been replaced by category STANDARD.
The concept of a default rule has been introduced. A default rule is a rule that will be run
if no rules are explicitly configured in your buf.yaml. Run buf config ls-lint-rules or
buf config ls-breaking-rules to see which rules are defaults. With this introduction, having a category
also named DEFAULT is confusing, as while it happpens that all the rules in the DEFAULT category
are also default rules, the name has become overloaded.
As with all buf changes, this change …
```

feat(buf): bump to latest version

---

tools/sgcloudspanner/emulator.go

Use a background context with a 10s timeout when stopping the emulator.
This makes sure the container is (at least attempted) stopped when e.g. pressing ctrl-c while running tests.

fix(cloud-spanner): stop emulator container with background context

---

tools/sgcloudspanner/emulator.go

I'm not bumping all the way to 1.5.24 as we are seeing issues with Spanner on
macOS on versions released after 1.5.22.
I've added a note on this limitation/issue in our internal macOS tech-radar.
We should investigate and perhaps file an issue with
https://github.com/GoogleCloudPlatform/cloud-spanner-emulator

feat(spanner): bump to 1.5.22

---

tools/sgprotocgengoaiptest/tools.go

Version 0.27.0 introduces a new way to bootstrap AIP tests, see https://github.com/einride/protoc-gen-go-aip-test/pull/263 for more info.

feat(sgprotocgengoaiptest): bump to v0.27.0

---

tools/sgtrivy/tools.go

Looks like trivy was updated so that we can remove the ignore-comments about ssl
mode.
- https://github.com/aquasecurity/trivy-checks/releases/tag/v1.1.0
- https://github.com/aquasecurity/trivy/releases/tag/v0.56.0 (note the
chore(deps): Bump trivy-checks to v1.1.0)
But I also noticed that https://github.com/aquasecurity/trivy/pull/7564 is not
merged yet, so not really 100% sure about this.

feat(trivy): bump to v0.56.2

---

tools/sgcloudendpoints/tools.go

Reference:
https://github.com/GoogleCloudPlatform/esp-v2/releases/tag/v2.50.0

feat(sgcloudendpoints): bump to esp-v2 2.50.0

---

tools/sgcloudspanner/emulator.go

With v1.5.23, a new behavior is introduced where transactions will be
retried more often. This change will very likely reveal bugs where
resources, which are pointers, are mutated within the transaction in
such a way that these mutations persists at the beginning of a retried
transaction. Beware!

feat(spanner): bump to v1.5.24

---

tools/sgprotocgengoaiptest/tools.go

Introduces a new way to invoke the AIP tests, see this [PR](https://github.com/einride/protoc-gen-go-aip-test/pull/267).
Beware that this version will generate new test code.

feat(sgprotocgengoaiptest): bump to v0.28.0

---

tools/sgprotocgenopenapi/tools.go

So that we can generate openapiv3 JSON file from protos using `protoc-gen-openapi` and version control it from Sage.
Docs: https://github.com/google/gnostic/tree/main/cmd/protoc-gen-openapi

Add protoc-gen-openapi (from gnostic)

---

tools/sgcloudspanner/emulator.go

Fixes a bug introduced in b1b5e7ed8973dc6b8b858b9ac67b2081b2a27c72 (PR #594) where an empty context is used, which removes the logger.
Could be done cleaner with Go >=1.21 as can be seen in a TODO comment.
Before:
```
❯ make go-test
[sage] building binary and generating Makefiles...
[go-test] running Go tests...
[go-test] starting Cloud Spanner emulator...
[go-test] running Cloud Spanner emulator on 0.0.0.0:44611
[sage] stopping down Cloud Spanner emulator...
```
After:
```
❯ make go-test
[sage] building binary and generating Makefiles...
[go-test] running Go tests...
[go-test] starting Cloud Spanner emulator...
[go-test] running Cloud Spanner emulator on 0.0.0.0:46023
[go-test] stopping down Cloud Spanner emulator...
```

fix(spanner): use correct logger when stopping emulator

---

tools/sgmdformat/requirements.txt

Allows dependabot to also keep up with the version of the tool and
prevents surprise bumps when being run in various repositories

feat(sgmdformat): lock the version of the tool

---

tools/sgprettier/tools.go

This change should make it so pretiier does not return an error when a certain filetype is not found.

feat(sgprettier): don't fail when filetype not found.

---

tools/sggolangcilint/golangci.yml

[Wire](https://github.com/google/wire) is used a lot in our organization, but the linter is skipping all `wire.go` files due to them having a mandatory build tag.
This includes the build tag when running the linter, to make sure `wire.go` files are linted as well.
I would expect linter to break a lot of repos now, but likely with very easy fixes. Example:
```
❯ make go-lint
[sage] building binary and generating Makefiles...
[go-lint] running...
[go-lint]
internal/app/server/wire.go:61: File is not `gci`-ed with --skip-generated -s standard -s default (gci)
internal/app/server/wire.go:63: File is not `gci`-ed with --skip-generated -s standard -s default (gci)
[ ... code ... ]
internal/app/server/wire.go:62: File is not `gofumpt`-ed with `-extra` (gofumpt)
[ ... code ... ] …
```

feat(golangcilint): lint wire files

---

actions/setup/action.yml

Adds a new input to be able to checkout repos with submodules.
https://github.com/actions/checkout/blob/cbb722410c2e876e24abbe8de2cc27693e501dcb/README.md?plain=1#L117

feat(workflow): add option to checkout submodules in repo

---

Makefile
sg/makefile.go

If Sage is invoked in an environment where Go is not available in `$PATH`, Sage will download it.
This should not affect any users that has Go installed outside of an Sage repo.

feat: bump downloaded go to version 1.23.4

---

sgtool/build.go

When installing a go module which has made a major version bump,
e.g. example.com/foo => example.com/foo/v2,
just looking at the last element of the path to get the binary name
returns "v2" instead of "foo" (which is what 'go install' will name
the binary).
Instead use a 'go list' helper function to determine the name.

fix: use proper binary name for v2+ modules

---

actions/setup/action.yml

This prevents us from seeing outages where the image cannot be
downloaded

feat(gha): cache ko images

---

tools/sggopls/tools.go

[gopls](https://pkg.go.dev/golang.org/x/tools/gopls) supports running as a linter through the CLi with `gopls check <PATH_TO_GO_FILE> ...`

Add support to run `gopls check`

---

tools/sgapilinter/tools.go

This adds and fixes some AIP linters.
[v1.68.0](https://github.com/googleapis/api-linter/releases/tag/v1.68.0) says:
> update to min version to Go 1.22 (#1457) (f34f16b)
Could this be a blocker for upgrading sage on projects which are on Go < v.22 😬

feat(api-linter): bump to v1.69.1

---

tools/sgapilinter/tools.go

In https://github.com/googleapis/api-linter/releases/tag/v1.69.0
there was a breaking change to the api-linter's cli: it stopped
including current working directory as the proto path.
So it needs to be added here.

fix(sgapilinter): include proto path

---

tools/sggopls/tools.go

https://github.com/golang/tools/releases/tag/gopls/v0.18.0

feat(sggopls): bump to v0.18.0

---

tools/sgapilinter/tools.go

With api-linter v1.69.1, there was a side-effect/bug introduced which required us to add `--proto-path=.` to keep api-linter working. This side-effect/bug was fixed in v1.69.2.
We can keep `--proto-path=.` or remove it (hence the two separate commits) without issues, but I figured we should remove it.
- **feat(sgapilinter): bump with bugfix**
- **fix(sgapilinter): revert "include proto path"**
- https://github.com/googleapis/api-linter/releases/tag/v1.69.2
- https://github.com/googleapis/api-linter/issues/1465#issuecomment-2672414331

feat(sgapilinter): bump and revert

---

tools/sgosvscanner/tools.go

If approved this PR:
* Bumps osv-scanner tool to [latest version](https://github.com/google/osv-scanner/releases).
The sg tool hasn't been updated in some time and I'm running into issues using this for projects with patch go versions, as current version won't parse format `go 1.xx.xx` in `go.mod` and requires format `go 1.xx`. Works with newer versions of osv-scanner.

feat(sgosvscanner): bump to v1.9.2

---

tools/sgterraform/tfplan.go
tools/sgterraform/tools.go

Terraform is able to forget about resources (meaning remove from state
but leave real resource untouched) so we add support for this action.

feat(sgterraform): add support for "forget" action in terraform summary

---

.github/workflows/go.yml
.sage/go.mod
go.mod
sg/deps.go
sg/fn_test.go

If I'm not mistaken, the idea is that Sage should be compatible with Go projects
written with Go 1.17, given the contents of the `go.mod` file:
https://github.com/einride/sage/blob/master/go.mod#L3
However, there is code in the repo which requires newer Go versions.
- Bump minimum required Go version for using Sage to v1.22.
- Fix some linting issues which were required for passing CI.
- There will be instances that Go 1.22 won't be used, like with building `gopls` for example (which is fine, and actually pretty neat):
```
[sggopls:prepare-command] building golang.org/x/tools/gopls@v0.18.0...
[sggopls:prepare-command] go: golang.org/x/tools/gopls@v0.18.0 requires go >= 1.23.4; switching to go1.23.6
```
- There are some `gopls` linting warnings we might want to consider cleaning up?
``` …
```

Require Go 1.22 from now on

---

tools/sgbalenacli/tools.go

Balena starts printing warnings when the CLI has not been updated for
half a year, and exits with an error if it is a year old. The current
version is now 207 days old, so we are seeing warning prints in our
builds.
The CLI has changed a bit, so some usage may need to be updated. E.g:
- Deprecate `devices` supported command in favor of `device-type list`
- Deprecate `notes` command in favor of `device note`
- Deprecate `tunnel` command in favor of `device tunnel`
- Deprecate `env` add in favor of `env set`
- Deprecate `ssh` command in favor of `device ssh`
- Deprecate `logs` command in favor of `device logs`
- Deprecate `scan` command in favor of `device detect`
- Deprecate `orgs` command in favor of `organization list`
- Deprecate `tags` command in favor of `tag list`
- Deprecate `envs` …

feat!: bump balena-cli from v18 to v21

---

tools/sgterraform/tools.go

Getting the github comment makes it possible to post [Workflow Job Summaries](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#adding-a-job-summary) in your CI, like below:

feat(sgterraform): add PlanSummarized

---

tools/sggolangcilint/golangci.yml
tools/sggolangcilint/tools.go

```
golang.org/x/exp/maps.Keys() can be replaced by slices.AppendSeq(make([]T, 0, len(data)), maps.Keys(data)) exptostd  [96, 21]
```
https://golangci-lint.run/usage/linters/#exptostd

feat(golangci): add exptostd linter

---

actions/setup/action.yml

The Sage action today forces you to specify a specific Go version for your project. Would be nice if it would be able to read it from the `go.mod` instead.
Example, how it works today:
```yml
steps:
- name: Setup Sage
uses: einride/sage/actions/setup@master
with:
go-version: '1.24'
```
How it could work:
```yml
steps:
- name: Setup Sage
uses: einride/sage/actions/setup@master
with:
go-version-file: go.mod
```
- Add new action input `go-version-file` and pass it into the `go-version-file` of `actions/setup-go@v5`.
- Unfortunately, the `go-version` input has a default value, which is why I had to duplicate the `actions/setup-go@v5` step and add an if-condition to both of them. If you pass both a `go-version` and `go-version-file` value to `actions/setup-go@v5`, it will take the `go-version` …

feat: add `go-version-file` to sage composite action

---

Makefile
sg/makefile.go

As of Go 1.18 the -d flag for go get is deprecated and go get will always act as if the -d flag were enabled.
(#666 😈 )

fix: remove deprecated -d flag from go get

---

tools/sgprotocgentypescriptaip/tools.go

Release notes:
https://github.com/einride/protoc-gen-typescript-aip/releases/tag/v0.4.0

feat(sgprotocgentypescriptaip): bump to v0.4.0

---

tools/sgpoetry/command.go

The Poetry version used by sage is about a year old. Dependabot is using v2.x and it's likely a good idea to be on the same major version. 
- Change Sage's poetry version from v1.8.3 to v2.1.2.
- Dependabot is using v2.1.1 but I don't think that should matter.

feat(poetry): bump to latest version

---

.sage/main.go
internal/codegen/imports.go
tools/sgartifactregistry/auth.go
tools/sggolangcilintv2/golangci.yml.tmpl
tools/sggolangcilintv2/tools.go

Golangci-lint was bumped to v2.
- Add `sggolangcilintv2` as there are backwards braking changes to the CLI. The CLI arguments will differ from golangci-lint v1 and options around exclusion paths have been moved from the CLI so they must be defined in the config yaml.
- Deprecate `sggolangcilint`.
- Use golangci-lint v2.1.1.
- Run `golangci-lint migrate -c golangci.yml`. This sorted the linters for us, so they are now in alphabetical order. The `gci`, `gofumpt` linters were removed (now exists as formatters) and `gosimple` has been absorbed by `staticcheck`.
- Add comments back in which were removed by the migration tool.
- Address new linting issues found by golangci-lint.
- Use templating to allow per-project customization.
- Formatting capabilities: …

feat(sggolangcilintv2): add golangci-lint v2

---

.sage/main.go
tools/sggolangcilintv2/golangci.yml.tmpl
tools/sggolangcilintv2/tools.go

Golangci-lint v2 offers Go file formatting (docs/details on this [here](https://golangci-lint.run/usage/formatters/)), which is nice, as we don't have to chain the different formatters manually, or for example run only `golines` as formatter (which was the case in this repo). This can instead be delegated to golangci-lint and configured in the config yaml.
I think that this could nicely formalize how we expect formatting in CI.
- add formatters to config file template along with "sane and default" config values
- add functions for formatting; `sggolangcilintv2.Fmt` which writes the files.
- replace golines as formatter with `sggolangcilintv2.Fmt` here in the sage repo.
- This PR supersedes https://github.com/einride/sage/pull/662
- Add argument `--diff` if you want `sggolangcilintv2.Fmt` …

feat(sggolangcilintv2): add formatting

---

tools/sggolangcilint/tools.go
tools/sggolangcilintv2/tools.go

according to docs https://go.dev/ref/mod#vcs-dir
```For example, if a repository has large files checked into a testdata directory,
the module author could add an empty go.mod file in testdata so their users don’t
need to download those files.
```
This adds support for sggolangcilint module to ignore folders containing empty go.mod files.

feat(sggolangcilint): add support for empty go.mod files

---

actions/setup/action.yml

In one of our repos this made the time linting go down from about `1min` to `4s`.

perf(ci/setup-sage): include golangci-lint cache in sage cache

---

tools/sguv/command.go

Uv is a lot faster than poetry and comes with more functionality built-in. One particular feature is it downloads the Python version the project requires for you.
Also, since sgpoetry is installed by sgpython which reuses the local python installation, we don't get deterministic installations. This has caused issues for newly onboarded team members. Uv manages python installations, using uv finally gives us much better control in this regard.
Add uv!
- In draft until we know we want it like this.
- Docs: https://docs.astral.sh/uv/
- Add it to your project:
```go
// .sage/sagefile.go
func UvVersion(ctx context.Context) error {
sg.Logger(ctx).Println("checking uv version")
return sguv.Command(ctx, "version").Run()
}
```
- Works on my machine™

feat: add uv

---

tools/sggolangcilintv2/tools.go

I noticed that when calling `sggolangcilintv2.Run()` (executed from the git root), golangci-lint would start linting other `.sage` folders deeply nested in my project. This never happens in CI, but it happens sometimes locally. 
This was difficult to catch from the log output.
- Add log around the folder golangci-lint will execute in.
We can pass in exclusion rules for the `golangci.yml` generation, but this does not control in which folders golangci-lint gets executed. I started dabbling with automatically ignoring other `.sage` folders [here](https://github.com/einride/sage/blob/ec6f97543c63eded51d43fd7f5ffa55e724a9ee7/tools/sggolangcilintv2/tools.go#L251), but eventually threw that away as I think the config became too complex and started assuming things about the user's setup. I'm now …

feat(sggolangcilintv2): log which folder is being linted

---

sg/makefile.go
sgtool/file.go
tools/sgcloudrun/config.go
tools/sggolangcilintv2/golangci.yml.tmpl

Formatting does not currently work, when running `sggolangcilintv2.Fmt` due to wrong indentations in the yaml template.
- Fix indentation in config file.
- Also fix formatting issues that are now surfacing, as we are linting/formatting this repo properly.

Fix wrong yaml indentation

---

tools/sgprotocgengoaiptest/tools.go

https://github.com/einride/protoc-gen-go-aip-test/releases/tag/v0.32.0
This is related to this change https://github.com/einride/aip-go/pull/348

feat(sgprotocgengoaiptest): bump to v0.32.0

---

tools/sgterraform/tools.go

We have previously used "Replace" to try and make it clear that a
resource was being replaced rather than just being destroyed and/or
added however that can be a little confusing as Terraform itself does
not use any such concept in their plans and it runs the risk of
someone missing the fact that a resource is being destroyed.
So in this commit we instead add the resource to the list of resources
being added and created when a resource is being "replaced".

feat(sgterraform): change comment summary to use "destroy" and "add" instead of replace

---

sg/path.go
tools/sgcloudspanner/emulator.go
tools/sggolangcilintv2/tools.go
tools/sgpostgres/local.go

https://golangci-lint.run/docs/product/changelog/#v240

fix: bump golangci-lint to 2.4.0 to support go1.25 and fix lint issues

---

tools/sggolangcilintv2/tools.go

tried migrating a project to sggolangcilintv2 and got an error about handling empty go.mod files

Handles empty go.mod in sggolangcilintv2.Run

---

tools/sgconvco/tools.go

Had a problem where the download of v0.6.1 would not work... but it works now. But I already prepared this so, yeah, maybe let's merge it in. 😆

feat(sgconvco): bump to v0.6.2

---

actions/setup/action.yml

- Any new branch will not get a cache hit, resulting in a long waiting time in CI. I just opened a new PR in a brand new repo with very little inside and had to wait 8 minutes.
- This note is not true, as any new branch will create a new PR:
https://github.com/einride/sage/blob/cb68491e03eb2ab997ea7dd6d6287b13698d605d/actions/setup/action.yml#L69
- Update the cache keys and restore keys, so that we are much more likely to always get a cache hit (even if it is partial). This is how GitHub Actions cache is meant to be set up.
- Are there any concerns with this approach?
- [GHA caching docs](https://docs.github.com/en/actions/reference/workflows-and-actions/dependency-caching)

fix(action): increase cache hit chance
